#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Regenerate .dsh/.cordis.patch.generated.yml + start.bat from environment
variables. Never embed credentials in source.

Required env vars (read at run-time; never written to repo):
  WORKSPACE           absolute path to the agent-person workspace root
                      (default: parent of the directory holding this script's
                       3rd/atlassian/ folder).
  JIRA_URL            e.g. https://inone.intra.nsfocus.com/jira
  JIRA_PERSONAL_TOKEN Personal Access Token for JIRA
  CONFLUENCE_URL      e.g. https://inone.intra.nsfocus.com/confluence
  CONFLUENCE_PERSONAL_TOKEN Personal Access Token for Confluence

Usage:
  set WORKSPACE=E:\\path\\to\\workspace
  set JIRA_PERSONAL_TOKEN=<your token>
  set CONFLUENCE_PERSONAL_TOKEN=<your token>
  python 3rd/atlassian/update_config.py
"""
from __future__ import annotations

import io
import os
import sys
from pathlib import Path


def resolve_workspace() -> str:
    env = os.environ.get('WORKSPACE')
    if env:
        return env
    return str(Path(__file__).resolve().parent.parent.parent)


def read_env(name: str) -> str:
    return os.environ.get(name, '').strip()


def build_patch(workspace: str, jira_token: str, confluence_token: str) -> str:
    ws_url = workspace.replace('\\', '/')

    if jira_token and confluence_token:
        atlassian_env_lines = (
            '        env:\n'
            f'          JIRA_URL: "{read_env("JIRA_URL")}"\n'
            f'          JIRA_PERSONAL_TOKEN: "{jira_token}"\n'
            f'          CONFLUENCE_URL: "{read_env("CONFLUENCE_URL")}"\n'
            f'          CONFLUENCE_PERSONAL_TOKEN: "{confluence_token}"\n'
        )
    else:
        atlassian_env_lines = '        env: {}\n'

    return (
        '# Auto-generated by start.bat / update_config.py\n'
        '# Do not edit - regenerated on each launch\n'
        '\n'
        '- insert:\n'
        '    - id: nf-system-prompt\n'
        f'      name: "file:///{ws_url}/packages/nf-system-prompt/src/index.ts"\n'
        '    - id: nf-hooks\n'
        f'      name: "file:///{ws_url}/packages/nf-hooks/src/index.ts"\n'
        '    - id: mcp-nf-simple\n'
        "      name: '@deepseek-ai/dsh-mcp-client'\n"
        '      config:\n'
        '        transport: stdio\n'
        '        serverName: nf_simple\n'
        '        command: python\n'
        '        args:\n'
        '          - .dsh/3rd/nf_simple/nf_simple.py\n'
        f'        cwd: "{ws_url}"\n'
        '        env: {}\n'
        '        toolCallTimeoutMs: 120000\n'
        '        failOnStartupError: false\n'
        '    - id: mcp-atlassian\n'
        "      name: '@deepseek-ai/dsh-mcp-client'\n"
        '      config:\n'
        '        transport: stdio\n'
        '        serverName: atlassian\n'
        '        command: python\n'
        '        args:\n'
        '          - .dsh/3rd/atlassian/atlassian_bridge.py\n'
        f'        cwd: "{ws_url}"\n'
        + atlassian_env_lines +
        '        toolCallTimeoutMs: 60000\n'
        '        failOnStartupError: false\n'
    )


def update_bat(bat_file: Path, jira_token: str, confluence_token: str) -> bool:
    if not bat_file.exists():
        return False
    bat = bat_file.read_text(encoding='utf-8')
    if 'mcp-atlassian' not in bat:
        return False
    old = 'echo         env: {} >> "%PATCH_FILE%"\n'
    if jira_token and confluence_token:
        new = (
            'echo         env: >> "%PATCH_FILE%"\n'
            f'echo           JIRA_URL: "{read_env("JIRA_URL")}" >> "%PATCH_FILE%"\n'
            f'echo           JIRA_PERSONAL_TOKEN: "{jira_token}" >> "%PATCH_FILE%"\n'
            f'echo           CONFLUENCE_URL: "{read_env("CONFLUENCE_URL")}" >> "%PATCH_FILE%"\n'
            f'echo           CONFLUENCE_PERSONAL_TOKEN: "{confluence_token}" >> "%PATCH_FILE%"\n'
        )
    else:
        new = old
    seg_start = bat.find('    - id: mcp-atlassian')
    seg_end = bat.find('echo [DSH] Starting', seg_start)
    if seg_start < 0 or seg_end < 0:
        return False
    seg = bat[seg_start:seg_end]
    seg_new = seg.replace(old, new, 1)
    bat_file.write_text(bat[:seg_start] + seg_new + bat[seg_end:], encoding='utf-8')
    return True


def main() -> int:
    workspace = resolve_workspace()
    patch_path = Path(workspace) / '.dsh' / '.cordis.patch.generated.yml'
    bat_path = Path(workspace) / 'start.bat'

    jira_token = read_env('JIRA_PERSONAL_TOKEN')
    confluence_token = read_env('CONFLUENCE_PERSONAL_TOKEN')

    patch_path.parent.mkdir(parents=True, exist_ok=True)
    patch_path.write_text(
        build_patch(workspace, jira_token, confluence_token),
        encoding='utf-8',
    )
    print('patch file updated OK')

    if update_bat(bat_path, jira_token, confluence_token):
        print('start.bat updated OK')
    else:
        print('start.bat: mcp-atlassian segment not found (skipped)')

    if not (jira_token and confluence_token):
        print(
            'NOTE: JIRA_PERSONAL_TOKEN / CONFLUENCE_PERSONAL_TOKEN not set;\n'
            '      mcp-atlassian was written with env: {}; start.bat must\n'
            '      export the tokens before launching dsh web.',
            file=sys.stderr,
        )
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
