#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""更新 start.bat 和 patch 文件，将 mcp-atlassian 的 env 填入令牌"""

import io

# 1. 更新 patch 文件
patch_file = r'E:\agent_assets\.dsh\.cordis.patch.generated.yml'
patch_content = (
    '# Auto-generated by start.bat \n'
    '# Do not edit - regenerated on each launch \n'
    ' \n'
    '- insert: \n'
    '    - id: nf-system-prompt \n'
    '      name: "file:///REDACTED_WORKSPACE_PATH/packages/nf-system-prompt/src/index.ts" \n'
    '    - id: nf-hooks \n'
    '      name: "file:///REDACTED_WORKSPACE_PATH/packages/nf-hooks/src/index.ts" \n'
    '    - id: mcp-nf-simple \n'
    "      name: '@deepseek-ai/dsh-mcp-client' \n"
    '      config: \n'
    '        transport: stdio \n'
    '        serverName: nf_simple \n'
    '        command: python \n'
    '        args: \n'
    '          - .dsh/3rd/nf_simple/nf_simple.py \n'
    '        cwd: "REDACTED_WORKSPACE_PATH" \n'
    '        env: {} \n'
    '        toolCallTimeoutMs: 120000 \n'
    '        failOnStartupError: false \n'
    '    - id: mcp-atlassian \n'
    "      name: '@deepseek-ai/dsh-mcp-client' \n"
    '      config: \n'
    '        transport: stdio \n'
    '        serverName: atlassian \n'
    '        command: python \n'
    '        args: \n'
    '          - .dsh/3rd/atlassian/atlassian_bridge.py \n'
    '        cwd: "REDACTED_WORKSPACE_PATH" \n'
    '        env:\n'
    '          JIRA_URL: "https://inone.intra.nsfocus.com/jira"\n'
    '          JIRA_PERSONAL_TOKEN: "REDACTED_JIRA_TOKEN"\n'
    '          CONFLUENCE_URL: "https://inone.intra.nsfocus.com/confluence"\n'
    '          CONFLUENCE_PERSONAL_TOKEN: "REDACTED_CONFLUENCE_TOKEN"\n'
    '        toolCallTimeoutMs: 60000 \n'
    '        failOnStartupError: false \n'
)
with io.open(patch_file, 'w', encoding='utf-8') as f:
    f.write(patch_content)
print("patch 文件已更新 ✅")

# 2. 更新 start.bat
bat_file = r'E:\agent_assets\start.bat'
with io.open(bat_file, 'r', encoding='utf-8') as f:
    bat = f.read()

old_env_line = 'echo         env: {} >> "%PATCH_FILE%"\n'
new_env_lines = (
    'echo         env: >> "%PATCH_FILE%"\n'
    'echo           JIRA_URL: "https://inone.intra.nsfocus.com/jira" >> "%PATCH_FILE%"\n'
    'echo           JIRA_PERSONAL_TOKEN: "REDACTED_JIRA_TOKEN" >> "%PATCH_FILE%"\n'
    'echo           CONFLUENCE_URL: "https://inone.intra.nsfocus.com/confluence" >> "%PATCH_FILE%"\n'
    'echo           CONFLUENCE_PERSONAL_TOKEN: "REDACTED_CONFLUENCE_TOKEN" >> "%PATCH_FILE%"\n'
)

# 只替换 mcp-atlassian 段内的 env: {} 行，保留 mcp-nf-simple 的 env: {}
seg_start = bat.find('    - id: mcp-atlassian')
if seg_start >= 0:
    seg_end = bat.find('echo [DSH] Starting', seg_start)
    seg = bat[seg_start:seg_end]
    seg_new = seg.replace(old_env_line, new_env_lines, 1)
    bat = bat[:seg_start] + seg_new + bat[seg_end:]
    with io.open(bat_file, 'w', encoding='utf-8') as f:
        f.write(bat)
    print("start.bat 已更新 ✅")
else:
    print("start.bat 中未找到 mcp-atlassian 段")